# Generated by Django 5.1 on 2024-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_inventory_store_inventory'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='item',
            field=models.ManyToManyField(to='stores.inventory'),
        ),
    ]
