# Generated by Django 5.1 on 2024-09-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0002_wishlistitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='is_fulfilled',
        ),
    ]
