# Generated by Django 5.1 on 2024-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_remove_wishlistitem_is_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='karma',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
