# Generated by Django 5.1 on 2024-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20240906_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='inventory',
        ),
        migrations.AddField(
            model_name='store',
            name='inventory',
            field=models.ManyToManyField(to='stores.inventory'),
        ),
    ]
