# Generated by Django 5.1 on 2026-01-04 12:01

from django.db import migrations
import random

def add_dummy_inventory(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    Inventory = apps.get_model('stores', 'Inventory')

    dummy_items = [
        {'item_name': 'Fresh Milk', 'price': 25.00},
        {'item_name': 'Baladi Bread', 'price': 5.00},
        {'item_name': 'Feta Cheese', 'price': 45.00},
        {'item_name': 'Mineral Water (1.5L)', 'price': 7.00},
        {'item_name': 'Cola Can', 'price': 15.00},
        {'item_name': 'Red Eggs (Pack of 10)', 'price': 55.00},
        {'item_name': 'Dark Chocolate', 'price': 35.00},
        {'item_name': 'Chips', 'price': 10.00},
        {'item_name': 'Yogurt', 'price': 8.00},
        {'item_name': 'Rice (1kg)', 'price': 30.00},
    ]

    inventory_objects = []
    for item in dummy_items:
        obj, created = Inventory.objects.get_or_create(
            item_name=item['item_name'],
            defaults={'price': item['price']}
        )
        inventory_objects.append(obj)

    # Assign inventory to stores
    # We will assign a random subset of items to each store to make it look a bit more realistic,
    # or just all items. The user said "dummy data for each marked inventory". 
    # Assumning "each store".
    
    stores = Store.objects.all()
    for store in stores:
        # Give each store 5 to all items
        if inventory_objects:
             # Random selection
             selected_items = random.sample(inventory_objects, k=random.randint(5, len(inventory_objects)))
             store.inventory.set(selected_items)

class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_update_cairo_stores'),
    ]

    operations = [
        migrations.RunPython(add_dummy_inventory),
    ]
